server {
    listen       ${PORT};
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /504.html;
    location = /504.html {
        root   /usr/share/nginx/html;
    }
}